### ISSUE TITLE
xiaomi.eu

### ISSUE THREAD

**Issue by ingbrzy** [ygorigor/Romanian_MIUI_V6#1]
Add me as collaborator here.. 

thanks

**Comment by ygorigor** [comment]
maybe will be bether to create another repo with translated xmls only
in this repo I have some changes for Redmi1

**Comment by ingbrzy** [comment]
as you want....

**Comment by ygorigor** [comment]
If you will have issues with this repo tell me and I will create another without device folder

**Comment by ingbrzy** [comment]
you have a lot of untranslatable strings translated.. please remove them all to avoid any bugs

http://translators.xiaomi.eu/XML_MIUI6-Romanian-ro.html

**Comment by ygorigor** [comment]
OK. I will

**Comment by ygorigor** [comment]
Done
